on:
  pull_request:
  merge_group:

name: Build

jobs:
  # Build with Ferrocene
  build-ferrocene:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install criticalup
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/ferrocene/criticalup/releases/download/v1.1.0/criticalup-installer.sh | sh
      - name: Install Ferrocene
        env:
          CRITICALUP_TOKEN: ${{ secrets.CRITICALUP_TOKEN }}
        run: |
          criticalup install
      - name: Build
        run: |
          criticalup run cargo build
          criticalup run cargo build --release

  # Build with upstream Rust's stable channel
  build-stable:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Rust
        run: |
          rustup toolchain install stable
          rustup target add armv8r-none-eabihf --toolchain=stable
      - name: Build
        run: |
          cargo +stable build
          cargo +stable build --release

  # Format the workspace
  fmt:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install rust
        run: |
          rustup install stable
          rustup component add rustfmt --toolchain=stable
      - name: Format
        run: |
          cargo +stable fmt --check

  # Gather all the above xxx-all jobs together for the purposes of getting an overall pass-fail
  all:
    runs-on: ubuntu-24.04
    needs: [build-ferrocene, build-stable, fmt]
    steps:
      - run: /bin/true
